create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text,
  balance integer not null default 2000 check (balance >= 0),
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  skin_name text not null,
  skin_value integer not null check (skin_value >= 0),
  skin_image text,
  created_at timestamptz not null default now()
);

create table if not exists public.game_stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  cases_opened integer not null default 0,
  spins integer not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  purchases integer not null default 0,
  sales integer not null default 0,
  total_spent bigint not null default 0,
  total_earned bigint not null default 0
);

alter table public.profiles enable row level security;
alter table public.inventory enable row level security;
alter table public.game_stats enable row level security;

create policy "Users can read their profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can create their profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update their profile" on public.profiles for update using (auth.uid() = id);
create policy "Users can manage their inventory" on public.inventory for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can manage their stats" on public.game_stats for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
